# Generated by Django 4.2.1 on 2023-06-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YgeatModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_img', models.CharField(max_length=200, verbose_name='图片地址')),
                ('eat_content', models.CharField(max_length=50, verbose_name='描述')),
                ('eat_time', models.CharField(max_length=20, verbose_name='时间')),
                ('hot', models.IntegerField(verbose_name='热度')),
            ],
            options={
                'verbose_name': '吃喝玩乐',
                'verbose_name_plural': '吃喝玩乐',
                'db_table': 't_ygeat',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='编码')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('grade', models.IntegerField(default=1, verbose_name='等级')),
                ('picture_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片路径')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commondity.categorymodel', verbose_name='父类')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 't_category',
            },
        ),
    ]
