# Generated by Django 4.2.1 on 2023-06-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commondity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commondity.categorymodel', verbose_name='父类'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片路径'),
        ),
    ]
