# Generated by Django 4.2.1 on 2023-06-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondity', '0002_alter_categorymodel_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YgeatModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_img', models.CharField(max_length=200, verbose_name='图片地址')),
                ('eat_content', models.CharField(max_length=50, verbose_name='描述')),
                ('eat_time', models.CharField(max_length=20, verbose_name='时间')),
                ('hot', models.IntegerField(verbose_name='热度')),
            ],
            options={
                'verbose_name': '吃喝玩乐',
                'verbose_name_plural': '吃喝玩乐',
                'db_table': 't_ygeat',
            },
        ),
    ]
