# Generated by Django 4.2.1 on 2023-06-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('commondity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 't_tag',
            },
        ),
        migrations.CreateModel(
            name='SiwapModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_img', models.CharField(max_length=200, verbose_name='活动大图')),
                ('active_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actives', to='address.activesmodel', verbose_name='活动表')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
                'db_table': 't_siwap',
            },
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('goods_code', models.CharField(max_length=30, verbose_name='编号')),
                ('maxcount', models.IntegerField(verbose_name='最大购买数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('goods_hot', models.IntegerField(verbose_name='热度')),
                ('categoryid', models.ManyToManyField(db_table='t_goods_cate', related_name='goods_cate', to='commondity.categorymodel', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 't_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfoModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_info', models.CharField(max_length=200, verbose_name='商品说明')),
                ('sellprice', models.FloatField(verbose_name='折扣价')),
                ('subtitle', models.CharField(max_length=200, verbose_name='副标题')),
                ('unit', models.CharField(max_length=20, verbose_name='规格')),
                ('spec', models.CharField(max_length=30, verbose_name='单位/规格')),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频')),
                ('placeoforgin', models.CharField(max_length=100, verbose_name='产地')),
                ('goods_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='goods.goodsmodel', verbose_name='商品id')),
                ('promotiontag', models.ManyToManyField(db_table='tag_goods_info', related_name='goods_tag', to='goods.tagmodel', verbose_name='标签名')),
            ],
            options={
                'verbose_name': '商品详情表',
                'verbose_name_plural': '商品详情表',
                'db_table': 't_goods_info',
            },
        ),
        migrations.CreateModel(
            name='GoodsImageModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=200, verbose_name='商品图片')),
                ('goods_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='goods.goodsmodel', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 't_goods_image',
            },
        ),
    ]
