# Generated by Django 4.2.1 on 2023-06-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiwapModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_img', models.CharField(max_length=200, verbose_name='活动大图')),
                ('active_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actives', to='address.activesmodel', verbose_name='活动表')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
                'db_table': 't_siwap',
            },
        ),
    ]
