# Generated by Django 4.2.1 on 2023-06-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('anth_key', models.CharField(max_length=100, verbose_name='口令')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.CharField(max_length=50, verbose_name='邮件')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('status', models.IntegerField(choices=[(2, '已注销'), (1, '已激活'), (0, '未激活')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 't_app_user',
            },
        ),
    ]
