# Generated by Django 4.2.1 on 2023-06-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('cartlist', '0001_initial'),
        ('commondity', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('image', models.CharField(max_length=200, verbose_name='导航图片')),
                ('actives_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Navs', to='address.activesmodel', verbose_name='活动ID')),
                ('nav_child_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='commondity.categorymodel', verbose_name='分类ID')),
            ],
            options={
                'verbose_name': '导航表',
                'verbose_name_plural': '导航表',
                'db_table': 't_nav',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=500, verbose_name='评论内容')),
                ('comment_time', models.CharField(max_length=30, verbose_name='评论时间')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_comment', to='cartlist.orderlistmodel', verbose_name='订单ID')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
                'db_table': 't_comments',
            },
        ),
    ]
