# Generated by Django 4.2.1 on 2023-06-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='img1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='status',
            field=models.IntegerField(choices=[(2, '已注销'), (1, '已激活'), (0, '未激活')], default=0, verbose_name='状态'),
        ),
    ]
