# Generated by Django 4.2.1 on 2023-06-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser_img1_alter_appuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
    ]
