# Generated by Django 4.2.1 on 2023-06-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_appuser_img1'),
        ('address', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderlistModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.CharField(max_length=50, verbose_name='下单时间')),
                ('order_statues', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已取消'), (3, '待发货'), (4, '已发货'), (5, '已完成')], verbose_name='订单状态')),
                ('addr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addrs', to='address.addressmodel', verbose_name='订单地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user.appuser', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 't_orderlist',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='购买数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='goods.goodsmodel', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='cartlist.orderlistmodel', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单商品详情表',
                'verbose_name_plural': '订单商品详情表',
                'db_table': 't_ordergoods',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='goods.goodsmodel', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.appuser', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 't_cart',
            },
        ),
    ]
